"use strict";

module.exports = {
    "application_type": ["oidcAppType"],
    "backchannel_logout_uri": ["oidcBackChannelLogoutURI", {"attribute": "labeledURI", "label": "backchannel_logout"}],
    "backchannel_logout_session_required": ["oidcBackChannelLogoutSessionRequired"],
    "client_id": ["oauthClientID", "cn", "commonName"],
    "client_id_issued_at": ["oauthClientIDIssueTime"],
    "client_secret": ["oauthClientSecret", "userPassword"],
    "client_secret_expires_at": ["oauthClientSecretExp", "pwdMaxAge"],
    "client_uri": ["oauthClientURI", {"attribute": "labeledURI", "label": "homepage"}],
    "contacts": ["mail", "rfc822Mailbox"],
    "default_acr_values": ["oidcDefaultACR"],
    "default_max_age": ["oidcDefaultMaxAge"],
    "grant_types": ["oauthGrantType"],
    "id_token_encrypted_response_alg": ["oidcIDTokenJWEAlg"],
    "id_token_encrypted_response_enc": ["oidcIDTokenJWEEnc"],
    "id_token_signed_response_alg": ["oidcIDTokenJWSAlg"],
    "initiate_login_uri": ["oidcInitiateLoginURI", {"attribute": "labeledURI", "label": "initiate_login"}],
    "jwks": [{"attribute": "oauthJWKSet", "json": true}],
    "jwks_uri": ["oauthJWKSetURI", {"attribute": "labeledURI", "label": "jwks"}],
    "logo_uri": ["oauthLogoURI", {"attribute": "labeledURI", "label": "logo"}],
    "policy_uri": ["oauthPolicyURI", {"attribute": "labeledURI","label": "policy_uri"}],
    "redirect_uris": ["oauthRedirectURI", {"attribute": "labeledURI", "label": "redirect"}],
    "post_logout_redirect_uris": ["oidcPostLogoutRedirectURI", {"attribute": "labeledURI", "label": "logout_redirect"}],
    "request_object_encryption_alg": ["oidcRequestJWEAlg"],
    "request_object_encryption_enc": ["oidcRequestJWEEnc"],
    "request_object_signing_alg": ["oidcRequestJWSAlg"],
    "request_uris": ["oidcRequestURI", {"attribute": "labeledURI", "label": "request"}],
    "require_auth_time": ["oidcRequireAuthTime"],
    "response_types": ["oauthResponseType"],
    "sector_identifier_uri": ["oidcSectorIdentifierURI", {"attribute": "labeledURI", "label": "sectorid"}],
    "subject_type": ["oidcSubjectType"],
    "token_endpoint_auth_method": ["oauthTokenEndpointAuthMethod"],
    "token_endpoint_auth_signing_alg": ["oauthTokenEndpointJWSAlg"],
    "tos_uri": ["oauthTermsOfServiceURI", {"attribute": "labeledURI", "label": "tos"}],
    "userinfo_encrypted_response_alg": ["oidcUserInfoJWEAlg"],
    "userinfo_encrypted_response_enc": ["oidcUserInfoJWEEnc"],
    "userinfo_signed_response_alg": ["oidcUserInfoJWSAlg"]
};
